language: elixir
elixir: 1.10
otp_release: 22.0
services:
  postgresql
jobs:
  include:
    - stage: test
      elixir: 1.8
      otp_release: 21.0
      script: &test_scripts
        - mix test
        - MIX_ENV=test mix credo
    - stage: test
      script: *test_scripts
    - stage: test
      script: *test_scripts
      env:
        - UUID=true
